name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "cuentafrst@gmail.com"
          git config --global user.name "Armando"

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -g web-ext

      - name: Build extension
        run: pnpm build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Video Tools v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload XPI to Release
        id: upload_xpi
        uses: actions/upload-artifact@v2
        with:
          name: video-tools.xpi
          path: dist/video-tools.xpi

      - name: Attach XPI to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/video-tools.xpi
          asset_name: video-tools.xpi
          asset_content_type: application/zip